getwd()
dir.create("raw_data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results")
dir.create("plots")
data <- read.csv(file.choose())
View(data)
str(data)
data$gender_fac <-as.factor(data$gender)
str(data)
data$gender_num <- ifelse(data$gender_fac == "Female",1, 0)
class(data$gender_num)
data$smoker <- as.factor(data$smoker)
str(data)
data$smoker_num <- ifelse(data$smoker == "Yes",1, 0)
class(data$smoker_num)
write.csv(data, file = "patient_info_clean.csv")

